// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIdh4vplih6LnpBUXuKkGLi3KQHCcH0sM',
    appId: '1:49535013661:web:64cd3c0743f9cc67bc07f4',
    messagingSenderId: '49535013661',
    projectId: 'delivery-9967f',
    authDomain: 'delivery-9967f.firebaseapp.com',
    storageBucket: 'delivery-9967f.firebasestorage.app',
    measurementId: 'G-0VGHE7DJS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCij8j5HUap84b19M9MPvCmDaKnv_jpYyQ',
    appId: '1:49535013661:android:6478f2f7fb071f84bc07f4',
    messagingSenderId: '49535013661',
    projectId: 'delivery-9967f',
    storageBucket: 'delivery-9967f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDHywfkjyfQ0FcUB_RA83Mq1mPs8SLH0k',
    appId: '1:49535013661:ios:0d24b5ed5df76bedbc07f4',
    messagingSenderId: '49535013661',
    projectId: 'delivery-9967f',
    storageBucket: 'delivery-9967f.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIdh4vplih6LnpBUXuKkGLi3KQHCcH0sM',
    appId: '1:49535013661:web:43028b21ac2d7b04bc07f4',
    messagingSenderId: '49535013661',
    projectId: 'delivery-9967f',
    authDomain: 'delivery-9967f.firebaseapp.com',
    storageBucket: 'delivery-9967f.firebasestorage.app',
    measurementId: 'G-H74W71ESSH',
  );
}
